In [4]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [5]:
np_mat + np.array([10, 10])


array([[11, 12],
       [13, 14],
       [15, 16]])

In [6]:
np_mat + np_mat

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])